class CustomError(Exception):
    pass
raise CustomError("Testing Custom Error Here")